<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/main.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery.colorbox.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/member.js"></script> 
<link rel="stylesheet" href="<%=request.getContextPath()%>/front/css/colorbox.css" type="text/css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/front/css/style.css" type="text/css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/front/css/commonstyle.css" type="text/css" />